# .github/workflows/build-windows-exe.yml

name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'

jobs:
  build-exe:
    runs-on: windows-latest
    
    permissions:
      contents: write

    steps:
      # 1. Code aus dem Repository laden
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python-Umgebung einrichten
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Alle Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # 4. Die Übersetzungsdateien (.mo) kompilieren
      - name: Compile translations
        run: python src/pdf_annotation_extractor/compile_translations.py

      # 5. PyInstaller ausführen, um die .exe zu erstellen
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed `
            --name "pdf-annotation-extractor" `
            --icon "assets/icon.ico" `
            --add-data "src/pdf_annotation_extractor/locale;pdf_annotation_extractor/locale" `
            --paths "src" ` # <-- HIER IST DIE WICHTIGE ÄNDERUNG
            src/pdf_annotation_extractor/main.py

      # 6. Release auf GitHub erstellen und die .exe als Anhang hochladen
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/pdf-annotation-extractor.exe
